### ISSUE TITLE
Open URLs

### ISSUE THREAD

**Issue by archusr** [craigbarnes/showdown#52]
Being able to render remote MarkDown resources, this _Simple Markdown viewer_ **_Showdown_** would be **the** web browser for the textual web!

**Comment by craigbarnes** [comment]
> the web browser for the textual web

I don't think there really is much of a textual web though. Almost no one hosts their Markdown files with the proper content type (`text/markdown` or `text/x-markdown`) and very few people seem to author content with this usage in mind. Most Markdown seems to be authored with the assumption that it'll be converted to and published as some other format. 

For me, Showdown is just a tool for quickly checking and viewing source documents -- not a substitute for a web browser or full blown document viewer. The reason I made it as a separate app and not a browser extension is because, for a simple viewer, most browser features are redundant and just clutter up the interface. If you go down the route of implementing full browsing, remote document loading, etc. -- at that point it may as well be implemented as a browser extension. I've thought about doing this myself before, but I've never had sufficient need for it to justify working on it.

**Comment by archusr** [comment]
Thanks for your thoughts on that! I'm gonna have an eye open for such browser extensions, although the the attraction was indeed the uncluttured interface.
